title: "hzzg0727 Blog :squirrel:"
email: 3190101611@zju.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Record the life, techniques, and others on the road.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hzzg0727.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: None
github_username:  hzzg0727

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Minimal mistakes theme settings
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "zh"
# subtitle: "On the Road"
name: "hzzg0727"
search: true
words_per_minute: 120
      
author:
  name: "hzzg0727"
  avatar: "/assets/images/paddington_avatar.jpg"
  bio: "On the road." # Note: Markdown is allowed
  location: "Hangzhou, China"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hzzg0727"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hzzg0727"

atom_feed:
  hide: true

paginate: 5

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      toc: true
      toc_label: "Table of Contents"
      toc_icon: "cog"
      toc_sticky: true
      classes: wide
  - scope:
      path: ""
      type: tag
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      toc: true
      toc_label: "Table of Contents"
      toc_icon: "cog"
      toc_sticky: true
  - scope:
      path: ""
      type: category
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      toc: true
      toc_label: "Table of Contents"
      toc_icon: "cog"
      toc_sticky: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      # layout: single
      author_profile: true
      comments: false
      share: false
      toc: false
      classes: wide

include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax

# head_scripts:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML